apiVersion: cloudkit.openshift.io/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    app.kubernetes.io/name: cloudkit-operator
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachine-sample
spec:
  # TODO(user): Add fields here
